# Generated by Django 3.0.4 on 2020-04-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FromLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], max_length=2)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
