# Generated by Django 3.0.4 on 2020-04-11 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_auto_20200410_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='lang_2',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translate',
            name='text_2',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
    ]
