# Generated by Django 3.0.4 on 2020-04-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_auto_20200411_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate',
            name='text_2',
        ),
    ]
