# Generated by Django 3.0.4 on 2020-04-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0004_remove_translate_text_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translate',
            old_name='text_1',
            new_name='text',
        ),
    ]
