# Generated by Django 3.0.4 on 2020-04-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0008_auto_20200412_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='translated_text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
