# Generated by Django 3.0.4 on 2020-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0009_auto_20200412_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='translated_text',
            field=models.CharField(max_length=500),
        ),
    ]
