# Generated by Django 3.0.4 on 2020-04-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0014_auto_20200413_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate',
            name='translation',
        ),
        migrations.AddField(
            model_name='result',
            name='id_translate',
            field=models.IntegerField(default=0),
        ),
    ]
